[package]
authors = ["Ole Magnus Johnsen <ole.magnus@me.com>"]
name = "appwash-cli-rust"
description = "A command-line utility for AppWash"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
serde = { version = "*", features = ["derive"] }
chrono = "0.4.19"
xdg = "*"
colored = "*"
rust-ini = "0.18"

[dependencies.clap]
version = "3.1"
features = ["suggestions", "color", "wrap_help", "cargo", "unstable-grouped"]
